### ISSUE TITLE
Is wasdk.github.io/wasmcodeexplorer broken?

### ISSUE THREAD

**Issue by paolosevMSFT** [wasdk/wasmcodeexplorer#9]
Since yesterday, the website shows an almost blank page.

**Comment by yurydelendik** [comment]
Thank you for the report. It is a regression after https://github.com/wasdk/wasmparser/pull/45

Fixed by f1646927025b17bc42fb04f57c8b5f2e6f4588c9

**Comment by paolosevMSFT** [comment]
Thanks!
